# coding: utf-8

"""
    oAuth

    oAuth para produção  # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oauth_itau
from oauth_itau.default_api import DefaultApi  # noqa: E501
from oauth_itau.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = oauth_itau.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_postoauthtoken(self):
        """Test case for postoauthtoken

        post /oauth/token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
