# coding: utf-8

"""
    oAuth

    oAuth para produção  # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import oauth_itau
from oauth_itau.oauth_model.oauth_cred import OauthCred  # noqa: E501
from oauth_itau.rest import ApiException


class TestOauthCred(unittest.TestCase):
    """OauthCred unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOauthCred(self):
        """Test OauthCred"""
        # FIXME: construct object with mandatory attributes with example values
        # model = oauth_itau.models.oauth_cred.OauthCred()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
