# coding: utf-8

# flake8: noqa
"""
    oAuth

    oAuth para produção  # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from oauth_itau.oauth_model.oauth_cred import OauthCred
