# coding: utf-8

# flake8: noqa

"""
    oAuth

    oAuth para produção  # noqa: E501

    OpenAPI spec version: 1.40.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from oauth_itau.oauth_itau.default_api import DefaultApi

# import ApiClient
from oauth_itau.api_client import ApiClient
from oauth_itau.configuration import Configuration
# import models into sdk package
from oauth_itau.oauth_model.oauth_cred import OauthCred
